branch-defaults:
  master:
    environment: project-reducto-dev
    group_suffix: null
global:
  application_name: project-reducto
  branch: null
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-east-1
  profile: eb-cli
  repository: null
  sc: git


